### ISSUE TITLE
Can't start admin

### ISSUE THREAD

**Issue by jnovotny** [lucidsoftware/piezo#35]
Hi,

I installed and ran the worker, however I have problems with admin

I installed latest PLAY https://www.playframework.com/

and made sure 'activator' is in my path. Then in admin after doing sbt compile and make stage, I do:

./bin/run.sh
Error: Could not find or load main class play.core.server.NettyServer

What am I missing?

Thanks

**Comment by disaacson** [comment]
@jnovotny I just updated the script. https://github.com/lucidsoftware/piezo/commit/97d6ef9815a185d071ca293979bd36de252fec4c

Make sure you run `make stage` first.
