### ISSUE TITLE
Edit job's data map seems buggy

### ISSUE THREAD

**Issue by pablote** [lucidsoftware/piezo#38]
When adding several data map variables sometimes only one gets added, sometimes none. What seems to work is adding one at the time.

Check out this vid: https://dl.dropboxusercontent.com/u/24172839/piezo-jobdatamap.mp4

thanks

**Comment by pablote** [comment]
I think I can see the reason this is happening, params posted seem to be stepping over each other. This is a sample post of two params as seen on Chrome network tab:

```
group:mq
name:pop-and-log
class:com.cinchcast.telephony.tasks.job.quartz.MqLoggingJob
description:Logs MQ messages
durable:true
job-data-map[0].key:mqHost
job-data-map[0].value:example.com
job-data-map[0].key:mqPort
job-data-map[0].value:1234
```

**Comment by lucidchart** [comment]
Thanks. I'd love a pull request to fix it.

Or, we may have time for someone to work on a bunch of the backlog items
this summer.

**Comment by marwtki** [comment]
Derrick thinks this is fixed. Please reopen if this is a problem.
