### ISSUE TITLE
Too many open files exception

### ISSUE THREAD

**Issue by disaacson** [lucidsoftware/piezo#59]
{"lvl":"WARN","lgr":"c.l.piezo.Worker$","thrd":"main","msg":"Exception caught writing heartbeat timestamp to file /var/run/piezo/workerHeartbeatFile)","ex":"java.io.FileNotFoundException: /var/run/piezo/workerHeartbeatFile (Too many open files) at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_72-internal] at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_72-internal] at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_72-internal] at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_72-internal] at java.io.FileWriter.<init>(FileWriter.java:90) ~[na:1.8.0_72-internal] at com.lucidchart.piezo.Worker$.writeHeartbeat(Worker.scala:87) [com.lucidchart.piezo-worker_2.11-1.14.jar:1.14] at com.lucidchart.piezo.Worker$.run(Worker.scala:59) [com.lucidchart.piezo-worker_2.11-1.14.jar:1.14] at com.lucidchart.piezo.Worker$.main(Worker.scala:34) [com.lucidchart.piezo-worker_2.11-1.14.jar:1.14] at com.lucidchart.piezo.Worker.main(Worker.scala) [com.lucidchart.piezo-worker_2.11-1.14.jar:1.14] "}

**Comment by tmccombs** [comment]
Closing because this is an old issue, and is most likely due needing to increase the system open files limit.
