### ISSUE TITLE
jobs page won't open

### ISSUE THREAD

**Issue by JohnHarrison** [lucidsoftware/piezo#60]
The jobs page is so heavy duty now that it frequently times out.  Also attempting to load it apparently fires off this query:
```SELECT * FROM job_history WHERE job_name='UserIndexer' AND job_group='AdminSearch' ORDER BY start DESC LIMIT 100```
which doesn't seem to run quickly.

It might be better to have a very lightweight jobs template and then load specific job histories on demand as needed.  Or maybe there is some way to make the query more efficient.

**Comment by pauldraper** [comment]
There actually was an index, though it hadn't been run in our internal environment. Related to #61
